name: 'Setup github/licensed'
description: 'Setup github/licensed for use in GitHub Actions workflows'
inputs:
  version:
    description: 'The github/licensed version to install'
    required: true
  install-dir:
    description: 'The target install directory for the github/licensed executable'
    default: '/usr/local/bin'
    required: false
runs:
  using: 'node12'
  main: 'lib/index.js'
